# -*- coding: utf-8 -*-
# AI 包 · 章节 1–4（Hook / 价值承诺 / 痛点代入 / ChatGPT）
# 每句元组：(en, zh, viz, demo_id, img_en, img_zh)
# demo_id: 0=不需要实操，1..8=对应实操卡编号
# img_en / img_zh 只写「本句场景」；host 角色卡前缀由 build.py 统一拼接，保证跨图一致。

LINES = [
    # ============ 章节 1 · Hook（0:00–0:15）============
    ("I built a social-media package I could sell to a local shop for a hundred dollars.",
     "我做了一套社媒服务包，可以报价一百美元卖给本地商家。", "成品亮出", 1,
     "holding up a printed folder bursting with printed social posts, seven square cards fanned out, price tag visible, confident grin",
     "举着一个塞满社媒卡片的文件夹，七张方形卡片扇形展开，价签清晰可见，自信微笑"),
    ("Seven posts, seven captions, one short video. No code, no agency jargon.",
     "七张帖子、七条文案、一条短视频。不写代码，不讲 agency 黑话。", "清单闪现", 1,
     "pointing at a clean list on screen reading seven posts, seven captions, one short video, bold checkmarks",
     "指向屏幕上的清晰清单：七张帖子、七条文案、一条短视频，粗体对勾"),
    ("You'll see the brief, the prompts, the files, the time log, and the exact client message.",
     "你会看到需求单、提示词、成品文件、时间记录，还有我会发给客户的原话。", "承诺交付", 1,
     "gesturing toward five labeled document icons arranged in a row on a dark desk, open palm inviting",
     "手指向深色桌面上排成一行的五个带标签文档图标，掌心向上邀请观看"),
    ("Three tools: ChatGPT, Canva, CapCut. That's the whole stack.",
     "三个工具：ChatGPT、Canva、CapCut。就这么简单。", "工具亮相", 0,
     "three glowing app logos floating above the desk, host shrugging casually, relaxed smile",
     "三个发光的 App 图标悬浮在桌面上方，主持人随意耸肩，轻松微笑"),

    # ============ 章节 2 · 价值承诺（0:15–0:30）============
    ("By the end, you'll know how to turn a vague request into one small offer.",
     "看完你会知道，怎么把一句模糊的需求变成一个能报价的小服务。", "价值承诺", 0,
     "leaning forward toward camera, hands framing an invisible box, earnest teaching expression",
     "身体前倾向镜头，双手比划一个无形的方框，认真讲解的表情"),
    ("I'm building it for a fictional neighborhood coffee shop, and showing every edit.",
     "我会给一家虚构的社区咖啡店做完整案例，每一次修改都给你看。", "案例设定", 1,
     "beside a laptop showing a cozy coffee shop storefront photo, finger tracing the shop name",
     "站在显示温馨咖啡店门头照片的笔记本旁，手指沿着店名划过"),
    ("Then I'll subtract my time and software costs, and see if a hundred dollars even makes sense.",
     "然后我会扣掉时间和软件成本，看看一百美元到底合不合理。", "算账预告", 0,
     "holding a calculator up next to a stopwatch, skeptical raised eyebrow",
     "把计算器和秒表举在一起，挑眉带点怀疑的表情"),
    ("No income screenshots. Just files, hours, and boundaries.",
     "没有收入截图。只有文件、工时和边界。", "反差强调", 0,
     "pushing away a fake golden income screenshot with the back of one hand, firm calm look",
     "用手背推开一张伪造的金色收入截图，坚定而平静的神情"),

    # ============ 章节 3 · 痛点代入（0:30–1:15）============
    ("Most people get stuck in exactly the same place with AI.",
     "大多数人用 AI 时，都卡在同一个地方。", "痛点切入", 0,
     "sitting back with arms crossed, slight frustrated half-smile, studio lights low",
     "双臂交叉靠坐，略带无奈的苦笑，棚灯调暗"),
    ("You buy another subscription, watch another tutorial, and still have nothing to sell.",
     "你又买一个订阅，又看一个教程，最后还是没有任何能卖的东西。", "共鸣代入", 0,
     "surrounded by floating subscription receipt icons, looking mildly overwhelmed, hand on forehead",
     "被悬浮的订阅账单图标包围，略显崩溃地手扶额头"),
    ("The problem isn't your tools. 'Make money with AI' is not an offer.",
     "问题不在工具。『用 AI 赚钱』根本不是一个服务报价。", "认知反转", 0,
     "writing 'MAKE MONEY WITH AI' on a whiteboard then striking it through hard with a red marker",
     "在白板上写下『MAKE MONEY WITH AI』，然后用红笔用力划掉"),
    ("A local business can't buy a tool list from you. It can buy seven posts.",
     "本地商家买不了你的一串工具名单，但他能买下周要用的七张帖子。", "具体对比", 0,
     "split screen, a long tool list on the left crossed out, seven neat post cards on the right, host between them",
     "分屏：左边一长串工具清单被划掉，右边七张整齐的帖子卡片，主持人站在中间"),
    ("So before I touch any AI, I set three rules: one audience, one problem, one folder.",
     "所以在我打开任何 AI 之前，先定三条规则：一个受众、一个问题、一个文件夹。", "规则确立", 2,
     "writing three numbered rules on the whiteboard, turning to camera and counting them on fingers",
     "在白板上写下三条编号规则，转身对镜头用手指逐条点数"),
    ("Our audience is office workers and students within two miles of the shop.",
     "我们的受众是店铺两英里内的上班族和学生。", "受众锁定", 2,
     "pointing at a simple map with a two-mile circle drawn around a coffee shop pin",
     "指向一张简单地图，咖啡店图钉周围画着两英里的圆圈"),
    ("The problem is next week's cold brew launch needs seven days of content.",
     "问题是下周的冷萃新品上市，需要七天的社媒内容。", "问题锁定", 2,
     "calendar on screen with seven consecutive days highlighted in brand color, host tapping day one",
     "屏幕上日历有连续七天被品牌色高亮，主持人点着第一天"),
    ("No promise of viral reach. No promise of guaranteed sales.",
     "不承诺爆款传播，也不承诺保证成交。", "边界声明", 0,
     "both hands raised palms out in a calm stop gesture, steady serious expression",
     "双手掌心向外做出平静的停止手势，神情稳重认真"),
    ("And no pretending the AI draft is ready to hand to a client.",
     "也不会把 AI 初稿假装成可以交给客户的成品。", "诚实提醒", 0,
     "holding up a crumpled AI draft printout beside a crisp final version, shaking head slightly",
     "一手举起皱巴巴的 AI 初稿打印件，另一手是平整的终稿，轻轻摇头"),
    ("That constraint is the whole point. If it can't survive a client review, it's not a business.",
     "这些限制才是重点。如果一份东西经不起客户审核，它就还不算生意。", "金句升华", 0,
     "pointing directly at camera, bright focused eyes, studio lights warming up",
     "直接指向镜头，眼神明亮专注，棚灯转暖"),
    ("Watch what happens when I actually follow it. We start with ChatGPT.",
     "看看我真的照做会发生什么。我们从 ChatGPT 开始。", "转入实操", 3,
     "turning to the monitor with ChatGPT open, rolling up sleeves, ready-to-work expression",
     "转向已打开 ChatGPT 的显示器，挽起袖子，准备开工的表情"),

    # ============ 章节 4 · ChatGPT 需求→文案（1:15–2:30）============
    ("Tool one is ChatGPT. I'm not asking it to write viral posts.",
     "第一个工具是 ChatGPT。但我不会只让它写爆款帖子。", "工具开场", 3,
     "typing slowly into the ChatGPT input box, side profile, focused",
     "侧面视角专注地在 ChatGPT 输入框里缓慢打字"),
    ("I paste a short brief: cold brew, opens at seven, student discount on Tuesdays.",
     "我先贴一份简短需求：卖冷萃、早上七点开门、周二有学生折扣。", "需求输入", 3,
     "screen showing a compact brief paragraph being pasted into ChatGPT, cursor blinking",
     "屏幕显示一段精简需求被粘贴进 ChatGPT，光标闪烁"),
    ("Then I ask for seven ideas in a table with five specific columns.",
     "然后我要求它用表格给出七个选题，包含五个明确的列。", "结构化要求", 3,
     "prompt text on screen requesting a seven-row table with five named columns",
     "屏幕上显示提示词，要求输出带五个命名列的七行表格"),
    ("Hook. Customer situation. One proof point. Call to action. What to verify.",
     "钩子、客户场景、一个可验证信息、行动号召，以及需要核实的地方。", "列头展示", 3,
     "five column headers appearing one by one on screen with a soft chime-like glow",
     "五个列头在屏幕上依次出现，带柔和的发光效果"),
    ("That last column matters most. Here's what came back, and here's what I rejected.",
     "最后一列最重要。这是它返回的内容，也是我删掉的部分。", "悬念铺垫", 3,
     "leaning in close to the monitor, one finger hovering over a suspicious table row",
     "身体凑近显示器，一根手指悬停在一行可疑的表格上"),
    ("It invented a five-star review. It invented a price. It claimed health benefits.",
     "它编了一条五星好评，编了一个价格，还宣称有健康功效。", "问题曝光", 3,
     "three table rows highlighted in red, host's face showing mild alarm",
     "三行表格被红色高亮，主持人露出轻微警觉的表情"),
    ("Three lines I delete immediately. A client would have shipped that.",
     "这三行我立刻删掉。换成客户，可能就直接发出去了。", "惊醒对比", 3,
     "pressing delete key with emphasis, then exhaling slowly, relieved but serious",
     "用力按下删除键，然后缓缓呼气，如释重负但神情严肃"),
    ("So I rewrite the prompt and regenerate only the rows that broke.",
     "于是我改写提示词，只重新生成出问题的那几行。", "修正动作", 3,
     "typing a revised instruction into ChatGPT, only two table rows selected",
     "在 ChatGPT 里输入修改后的指令，只选中两行表格"),
    ("Side by side: first draft on the left, corrected version on the right.",
     "并排对比：左边是第一版，右边是修改后的版本。", "对比展示", 3,
     "two-column comparison on screen, left panel marked FIRST DRAFT, right marked CORRECTED",
     "屏幕两栏对比，左栏标注 FIRST DRAFT，右栏标注 CORRECTED"),
    ("The value was never that first paragraph. It's the brief-to-draft process.",
     "价值从来不是那第一段文字，而是从需求到初稿的流程。", "认知升级", 0,
     "tapping temple with one finger, thoughtful expression, soft rim light",
     "一根手指轻点太阳穴，若有所思的表情，柔和轮廓光"),
    ("And it's checking every claim before a client ever sees it.",
     "还有在客户看到之前，逐条核对每一个说法。", "强调核查", 0,
     "moving a printed checklist across the desk, ticking boxes one by one",
     "把一张打印好的核对清单在桌上推过，逐格打勾"),
    ("I keep three ideas and ask for captions in the shop's plainspoken voice.",
     "我留下三个选题，再让它用这家店日常说话的口吻写文案。", "语气转换", 3,
     "screen showing a tone instruction being typed: plainspoken, short sentences, no exclamation marks",
     "屏幕显示正在输入语气指令：口语化、短句、不用感叹号"),
    ("Short sentences. No exclamation marks. Talk like the owner actually talks.",
     "短句，不用感叹号，就像老板平时说话那样。", "语气示例", 3,
     "before and after captions on screen, the after version noticeably plainer and shorter",
     "屏幕上前后两条文案对比，修改后明显更朴素更短"),
    ("Fifteen minutes on the brief, thirty-five on the captions.",
     "需求单花了十五分钟，文案花了三十五分钟。", "时间披露", 0,
     "stopwatch on screen showing fifty minutes elapsed, host glancing at it",
     "屏幕上秒表显示已过五十分钟，主持人瞥了一眼"),
    ("That's fifty minutes before a single image exists.",
     "也就是说，一张图都还没做，就已经花了五十分钟。", "节奏提示", 0,
     "empty Canva canvas on screen, host shrugging with a knowing smile",
     "屏幕上是空白的 Canva 画布，主持人会心耸肩微笑"),
    ("Here's the part nobody films: the AI draft is not the deliverable.",
     "这一段几乎没人拍：AI 初稿并不是交付物。", "反常识揭示", 0,
     "leaning toward camera, lowering voice, conspiratorial but warm expression",
     "倾向镜头，压低声音，像在说悄悄话但神情温暖"),
    ("The deliverable is the checked, edited, client-ready version.",
     "交付物是核对过、修改过、客户可以直接用的版本。", "定义交付", 0,
     "holding the final caption sheet up to the light, satisfied nod",
     "把最终的文案稿举到光下，满意地点头"),
    ("That gap is the skill. Now let's make the images, because Canva is where drafts become assets.",
     "这中间的差距才是本事。现在我们来做图，因为 Canva 才是把草稿变成资产的地方。", "转入下一章", 4,
     "switching the monitor to Canva with a decisive mouse click, leaning back ready",
     "果断点击鼠标把显示器切到 Canva，身体后靠准备开始"),
]
