# -*- coding: utf-8 -*-
# AI 包 · 章节 5–6（Canva 七张图 / CapCut 短视频）
# 每句元组：(en, zh, viz, demo_id, img_en, img_zh)

LINES = [
    # ============ 章节 5 · Canva 七张图（2:30–3:45）============
    ("Tool two is Canva. I build one 1080 by 1080 template first.",
     "第二个工具是 Canva。我先做一个 1080×1080 的模板。", "模板开场", 4,
     "creating a new square canvas in Canva, dimensions field showing 1080 by 1080",
     "在 Canva 里新建方形画布，尺寸栏显示 1080×1080"),
    ("Two brand colors, one typeface, logo locked in the same corner.",
     "两种品牌色、一个字体，Logo 固定在同一角落。", "规范建立", 4,
     "dragging a color swatch into the brand palette, logo snapping into the top-left corner",
     "把色块拖进品牌调色板，Logo 吸附到左上角"),
    ("Then I duplicate it seven times. I don't generate seven random designs.",
     "然后我把它复制七次。我不会生成七张风格各异的图。", "复制策略", 4,
     "right-clicking duplicate repeatedly, seven identical page thumbnails stacking in the sidebar",
     "反复右键复制，侧边栏里七张相同的页面缩略图依次堆叠"),
    ("Same layout, different photo, different headline, different call to action.",
     "版式一致，只换照片、标题和行动号召。", "变量说明", 4,
     "three identical layouts side by side with only photo and headline changing, arrows pointing",
     "三个相同版式并排，只有照片和标题在变，箭头指示变化处"),
    ("Consistency is what makes seven posts look like one campaign.",
     "正是这种一致性，让七张帖子看起来像同一个 campaign。", "理念点题", 0,
     "stepping back from the monitor, arms open, presenting the seven-page grid",
     "从显示器前退后一步，双臂张开展示七页网格"),
    ("I import one real product photo and remove the distracting background.",
     "我导入一张真实产品照片，把干扰的背景去掉。", "素材处理", 4,
     "using the background remover on a coffee cup photo, background vanishing smoothly",
     "对一张咖啡杯照片使用去背景功能，背景平滑消失"),
    ("Then I check the headline on a phone, because that's where it lives.",
     "然后我把标题放到手机上看，因为它最终就出现在手机上。", "手机校验", 4,
     "holding a phone up beside the monitor comparing the same headline at arm's length",
     "把手机举在显示器旁，一臂距离比较同一标题的可读性"),
    ("If I can't read it at arm's length, it goes back to the editor.",
     "如果一臂距离看不清，这张图就得回炉。", "验收标准", 4,
     "squinting at the phone screen, then shaking head and reaching for the mouse",
     "眯眼看手机屏幕，然后摇头伸手去拿鼠标"),
    ("Export with clean names: 01-monday-cold-brew through 07-sunday-reminder.",
     "导出时用规范命名：从 01-monday-cold-brew 一直到 07-sunday-reminder。", "命名规范", 4,
     "export dialog showing seven sequentially named PNG files in a neat column",
     "导出对话框显示七个按顺序命名的 PNG 文件，整齐排成一列"),
    ("Boring file names save you when a client asks for revision three.",
     "等客户要第三轮修改时，这些朴素的命名会救你一命。", "经验之谈", 0,
     "wry smile, tapping a neatly named file in the folder, knowing look at camera",
     "苦笑着轻点文件夹里一个命名规范的文件，对镜头投去了然的眼神"),
    ("If I need a stock photo, I label it and check the license.",
     "如果要用图库图，我会标明来源并检查授权。", "版权意识", 4,
     "a small credit label appearing under a stock photo, license badge visible",
     "图库照片下方出现小小的来源标注，授权徽章清晰可见"),
    ("If the shop doesn't have permission, the image does not go in the folder.",
     "如果店家没有授权，这张图就不会进交付文件夹。", "红线声明", 0,
     "firmly dragging a photo out of the delivery folder, decisive expression",
     "果断把一张照片拖出交付文件夹，表情坚定"),
    ("Next to the file I keep a five-box approval checklist.",
     "在文件旁边，我会放一张五项验收清单。", "清单引入", 5,
     "a compact checklist card appearing beside the Canva canvas with five empty boxes",
     "Canva 画布旁出现一张紧凑的清单卡，五个空方框"),
    ("Logo correct. Colors correct. Offer correct. Spelling checked. Image licensed.",
     "Logo 对、颜色对、活动信息对、拼写检查过、图片有授权。", "逐项朗读", 5,
     "five checkboxes filling with green ticks one after another",
     "五个复选框依次被绿色对勾填满"),
    ("If one box is empty, that page is not finished.",
     "只要有一格是空的，这一页就不算完成。", "硬性标准", 5,
     "one empty red-outlined box on the checklist, host pointing at it sternly",
     "清单上一个红色描边的空框，主持人严厉地指着它"),
    ("This is what turns a pretty design into something you can actually invoice.",
     "这才是把一张漂亮设计，变成你真的能开发票交付的东西。", "价值提炼", 0,
     "holding an invoice document next to the finished design grid, nodding",
     "把一张发票文件举在成品设计网格旁，点头"),
    ("Fifty-five minutes for the set of seven.",
     "七张套图花了五十五分钟。", "时间披露", 0,
     "stopwatch on screen crossing the fifty-five minute mark",
     "屏幕上秒表跨过五十五分钟刻度"),
    ("And now the asset a client can post tomorrow: a thirty-second vertical video in CapCut.",
     "现在来做客户明天就能发的素材：CapCut 里一条三十秒竖屏视频。", "转入下一章", 6,
     "switching to CapCut with a fresh project, vertical 9 by 16 canvas on screen",
     "切换到 CapCut 新建项目，屏幕上是 9:16 竖屏画布"),

    # ============ 章节 6 · CapCut 短视频（3:45–5:00）============
    ("Tool three is CapCut. I import three phone clips I shot myself.",
     "第三个工具是 CapCut。我导入三段自己拍的手机素材。", "素材导入", 6,
     "dragging three video clips into the CapCut media bin, thumbnails appearing",
     "把三段视频拖进 CapCut 素材箱，缩略图依次出现"),
    ("Pouring the cold brew. Pushing open the door. The finished cup.",
     "倒冷萃、推开店门、成品杯特写。", "镜头列举", 6,
     "three clip thumbnails lined up on the timeline, labeled pour, door, cup",
     "时间线上排列三段素材缩略图，分别标注倒、门、杯"),
    ("I cut the first second so the product appears immediately.",
     "我把第一秒剪掉，让产品立刻出现在画面里。", "节奏处理", 6,
     "trimming the head of the first clip, the cup now visible at frame one",
     "剪掉第一段素材的开头，第一帧就能看到杯子"),
    ("Attention is rented by the second, and I don't waste the first one.",
     "注意力是按秒租来的，我不会浪费第一秒。", "金句点题", 0,
     "snapping fingers, then pointing at the timeline start, sharp energetic look",
     "打了个响指，然后指向时间线起点，眼神锐利有神"),
    ("On-screen text matches the offer. Auto captions come next.",
     "屏幕文字和活动信息一致，然后生成自动字幕。", "字幕流程", 6,
     "adding on-screen text over the clip, then clicking the auto-caption button",
     "在片段上叠加屏幕文字，然后点击自动字幕按钮"),
    ("Then I read every caption line, because auto-caption gets names wrong.",
     "然后我逐行读字幕，因为自动字幕会把专有名词写错。", "人工核对", 6,
     "leaning close to the caption track, eyes scanning line by line, finger following",
     "凑近字幕轨道，眼睛逐行扫视，手指跟着移动"),
    ("It wrote 'cold brew' as 'cold blue'. A client would have posted that.",
     "它把『cold brew』写成了『cold blue』。换成客户，这就发出去了。", "错误示例", 6,
     "the wrong caption text highlighted in red on screen, host grimacing lightly",
     "屏幕上错误的字幕被红色高亮，主持人轻微皱眉"),
    ("Fix it, then watch the whole thing on my phone with the sound off.",
     "改完之后，我在手机上静音看一遍整条视频。", "静音验收", 6,
     "watching the phone screen with the phone muted, focused quiet expression",
     "手机静音状态下观看屏幕，专注而安静的表情"),
    ("If the story doesn't land silent, it won't land in a feed.",
     "如果静音时故事不成立，那它在信息流里也不会成立。", "判断标准", 0,
     "holding the phone up to camera, one eyebrow raised, making the point",
     "把手机举向镜头，挑起一边眉毛强调这个判断"),
    ("This is the failure point people skip: AI can assemble a video.",
     "这正是大家跳过的失败点：AI 确实能把视频拼出来。", "反常识揭示", 0,
     "leaning in, lowering voice slightly, serious teaching tone",
     "身体前倾，声音略微压低，认真的讲解语气"),
    ("It cannot know if the price, hours, or product name are correct.",
     "但它不知道价格、营业时间和商品名到底对不对。", "能力边界", 6,
     "a checklist of price, hours, product name on screen with a human hand ticking each",
     "屏幕上价格、营业时间、商品名清单，一只手逐项打勾"),
    ("That check is the job. That's what a client is actually paying for.",
     "这项核对才是工作本身，也是客户真正付钱买的东西。", "价值定义", 0,
     "pointing firmly at camera, confident steady gaze",
     "坚定地指向镜头，自信而沉稳的目光"),
    ("I export the MP4, keep the project file, and write a plain text caption.",
     "我导出 MP4，保留工程文件，再写一份纯文本文案。", "交付三件", 6,
     "three files in a row on screen: MP4, project file, plain text caption",
     "屏幕上并排三个文件：MP4、工程文件、纯文本文案"),
    ("Three files together, because 'here's a video' is not a delivery.",
     "三个文件放在一起，因为只说『视频给你』不算交付。", "交付理念", 0,
     "gathering the three files into one folder with a sweeping hand motion",
     "用扫拢的手势把三个文件收进同一个文件夹"),
    ("Forty-five minutes here, and twenty minutes of quality control after.",
     "这一步四十五分钟，后面还有二十分钟质检。", "时间披露", 0,
     "stopwatch showing forty-five minutes, then a quality control timer starting",
     "秒表显示四十五分钟，随后质检计时开始"),
    ("Now the part every 'make money with AI' video conveniently skips.",
     "现在来讲每个『用 AI 赚钱』视频都会故意跳过的一段。", "悬念铺垫", 0,
     "leaning toward camera with a slight smirk, preparing to reveal something",
     "带着一丝坏笑倾向镜头，准备揭晓什么"),
    ("The offer and the math. Let's add up the clock.",
     "报价和算账。我们来把时间加起来。", "转入算账", 7,
     "opening a spreadsheet titled TIME LOG, columns for task and minutes",
     "打开标题为 TIME LOG 的表格，列为任务和分钟"),
    ("Because if the numbers don't work, none of these files matter.",
     "因为如果数字算不过来，这些文件做得再好也没意义。", "强调重要", 0,
     "hands open on the desk, frank and unguarded expression",
     "双手摊开放在桌上，坦率不设防的表情"),
]
