# -*- coding: utf-8 -*-
# AI 包 · 章节 7–8（计时与报价 / 金句 + CTA）
# 每句元组：(en, zh, viz, demo_id, img_en, img_zh)

LINES = [
    # ============ 章节 7 · 计时与报价（5:00–6:15）============
    ("Fifteen minutes for the brief. Thirty-five for the captions.",
     "需求单十五分钟，文案三十五分钟。", "逐项计时", 7,
     "typing time entries into the spreadsheet, rows filling with minutes",
     "在表格里逐项录入时间，行内填充分钟数"),
    ("Fifty-five for the Canva set. Forty-five for the video.",
     "Canva 套图五十五分钟，视频四十五分钟。", "逐项计时", 7,
     "two more spreadsheet rows appearing, numbers stacking up",
     "表格里又出现两行，数字不断累加"),
    ("Twenty for quality control. Two hours and fifty minutes total.",
     "质检二十分钟。合计两小时五十分钟。", "合计披露", 7,
     "the total cell highlighting in yellow: two hours fifty minutes",
     "合计单元格黄色高亮：两小时五十分钟"),
    ("At a hundred dollars, that's about thirty-five dollars an hour gross.",
     "按一百美元算，毛时薪大约是三十五美元。", "关键数据", 7,
     "calculator on screen dividing one hundred by two point eight three hours",
     "屏幕上计算器用一百除以二点八三小时"),
    ("Before software, before taxes, before a single round of revisions.",
     "还没扣软件费、没扣税、一轮修改都还没开始。", "条件补充", 7,
     "three deduction icons dropping away from the hourly figure one by one",
     "三个扣除项图标从时薪数字上依次掉落"),
    ("So the offer has to be narrow, or the math quietly eats you.",
     "所以报价范围必须写得窄，否则账目会悄悄吃掉你。", "结论推导", 0,
     "drawing a tight boundary box around the scope list, concentrating",
     "在范围清单外画一个收紧的边界框，神情专注"),
    ("One round of revisions. Client supplies the logo and approved photos.",
     "只包含一轮修改。客户提供 Logo 和已授权的照片。", "范围条款", 7,
     "scope card on screen listing what is included and what the client must supply",
     "屏幕上范围卡列出包含项与客户须提供项"),
    ("Delivery in three days. No promise of followers or sales.",
     "三天交付。不承诺涨粉，也不承诺成交。", "交付条款", 7,
     "delivery timeline showing three days, with a crossed-out follower guarantee",
     "交付时间线显示三天，旁边是被划掉的涨粉承诺"),
    ("Five videos and daily posting is a different price, not a favor.",
     "要五条视频加每天代发，那是另一个价格，不是顺手帮忙。", "加价边界", 0,
     "shaking head firmly while a second price card slides onto the screen",
     "坚定摇头，同时第二张价格卡滑入屏幕"),
    ("I also put a revision counter on the sheet, and here's why.",
     "我还在表格里加了一列修改次数，原因在这儿。", "悬念铺垫", 7,
     "adding a revision counter column to the spreadsheet, pointing at it",
     "在表格里增加修改次数列，手指指向它"),
    ("If revision one takes ninety minutes, this is no longer a hundred-dollar job.",
     "如果第一轮修改花了九十分钟，这就已经不是一百美元的工作了。", "成本反转", 7,
     "ninety minutes typed into the revision column, the hourly rate visibly dropping",
     "九十分钟被录入修改列，时薪数字明显下降"),
    ("That's the moment to cut scope, raise the price, or walk.",
     "这时就该缩小范围、提高报价，或者干脆不做。", "行动选项", 0,
     "three decision cards on screen: cut scope, raise price, walk away",
     "屏幕上三张决策卡：缩范围、提价、退出"),
    ("Showing that boundary protects you from copying a fantasy hourly rate.",
     "把这条边界展示出来，能防止你去照抄一个幻想中的时薪。", "保护观众", 0,
     "open palm toward camera, protective and sincere expression",
     "掌心朝向镜头，带着保护意味又真诚的表情"),
    ("And it protects the client from a promise you can't keep.",
     "同时也保护客户，不让他们拿到一个你兑现不了的承诺。", "双向保护", 0,
     "two figures on screen, freelancer and client, both shielded under one umbrella",
     "屏幕上两个人物：自由职业者与客户，同在一把伞下"),
    ("This experiment is credible because I showed the cost, not a screenshot.",
     "这个实验可信，是因为我展示了成本，而不是甩一张截图。", "可信来源", 0,
     "pushing the time log forward, pulling the fake screenshot away",
     "把时间记录推到前面，把伪造截图推到一边"),
    ("You can disagree with my price. You can't say I hid the work.",
     "你可以不同意我的报价，但你不能说我藏了工作量。", "金句升华", 0,
     "steady gaze into camera, slight nod, warm confident half-smile",
     "沉稳地直视镜头，微微点头，温暖自信的浅笑"),
    ("So don't sell AI. Sell a finished file that removes one task.",
     "所以别卖 AI，要卖一个能替别人拿走一项任务的成品文件。", "核心金句", 0,
     "holding up the completed delivery folder, both hands, proud and open",
     "双手举起完成的交付文件夹，自豪而坦荡"),
    ("Let me say that again, because it's the whole video: don't sell the tool, sell the file.",
     "我再说一遍，因为这就是整条视频的重点：别卖工具，卖文件。", "强调重复", 0,
     "close-up on face, pointing to temple, text overlay SELL THE FILE",
     "脸部特写，手指指向太阳穴，画面叠加文字 SELL THE FILE"),

    # ============ 章节 8 · 金句 + CTA（6:15–7:00）============
    ("A local business doesn't want your prompt. It wants next week handled.",
     "本地商家想要的根本不是你的提示词，而是有人把下周搞定。", "换位思考", 0,
     "imagining a shop owner's desk piled with tasks, one of them being cleared away",
     "想象店主桌上堆满待办，其中一项被清走"),
    ("The brief template, prompt skeleton, naming checklist, and time log are in the description.",
     "需求单模板、提示词骨架、命名清单和时间记录表都放在简介里。", "资源承诺", 8,
     "four download cards appearing on screen with a downward arrow to the description",
     "屏幕上出现四张下载卡，向下的箭头指向简介区"),
    ("Use them on one fictional business first. Get the workflow in your hands.",
     "先拿一家虚构商家练手，把流程真正过一遍。", "行动建议", 8,
     "practicing on a sample folder labeled PRACTICE, relaxed encouraging nod",
     "在标注 PRACTICE 的示例文件夹上练习，放松鼓励地点头"),
    ("Then make one sample, and ask a real owner before using their brand.",
     "然后做一个样品；想用真实商家的品牌，一定先征得同意。", "授权提醒", 0,
     "showing a polite permission message draft on screen, thumb up",
     "屏幕上显示一封礼貌的授权请求草稿，竖起大拇指"),
    ("One personalized message beats fifty strangers in their inbox.",
     "一封个性化消息，胜过群发五十个陌生人。", "方法对比", 8,
     "one tailored email on the left outweighing fifty generic spam envelopes on the right",
     "左边一封定制邮件，压过右边五十封通用垃圾信封"),
    ("That's the difference between a side hustle and spam.",
     "这就是副业和垃圾信息的区别。", "价值判断", 0,
     "serious expression, hand cutting horizontally through the air",
     "神情严肃，手掌在空中横向一划"),
    ("Comment the kind of local business you'd build this for.",
     "在评论区告诉我，你想给哪类本地商家做这一套。", "评论互动", 8,
     "pointing downward toward the comment section, inviting smile",
     "指向下方评论区，发出邀请的微笑"),
    ("I'll pick one and run the whole workflow again on camera.",
     "我会挑一个，在镜头前把整套流程再跑一遍。", "下期预告", 0,
     "holding a marker over a blank whiteboard labeled NEXT EPISODE",
     "手持马克笔悬停在标注 NEXT EPISODE 的空白白板前"),
    ("And subscribe, because next time I'm showing the client feedback.",
     "顺手订阅，下期我会展示客户的真实反馈。", "订阅引导", 8,
     "hand forming a subscribe gesture beside a feedback email icon",
     "手比出订阅手势，旁边是反馈邮件图标"),
    ("Including the one revision that changed the price.",
     "包括那一次让报价发生变化的修改。", "悬念留白", 0,
     "a revised invoice on screen with the price noticeably changed, curious eyebrow raise",
     "屏幕上一张修改后的发票，价格明显变化，好奇地挑眉"),
    ("Don't sell the AI. Sell the file. I'll see you in the next one.",
     "别卖 AI，卖文件。我们下期见。", "收尾金句", 0,
     "final wide shot waving lightly at camera, delivery folder on the desk, studio lights warm",
     "最后全景镜头，向镜头轻轻挥手，桌上放着交付文件夹，棚灯温暖"),
]
