# -*- coding: utf-8 -*-
# 金融包 · 章节 5–6（三个案例 / 三个陷阱）
# 每句元组：(en, zh, viz, demo_id, img_en, img_zh)

LINES = [
    # ============ 章节 5 · 三个案例（2:30–3:45）============
    ("Case A: eight thousand on a twenty-two percent card, five hundred a month.",
     "案例 A：八千美元信用卡债，利率百分之二十二，每月还五百。", "案例A设定", 4,
     "case row A on screen with balance 8000, rate 22%, payment 500, host's cursor resting on it",
     "屏幕上案例 A 行：余额 8000、利率 22%、月供 500，主持人光标停在上面"),
    ("Case B: the same five hundred a month, but against a seven percent loan.",
     "案例 B：同样每月五百，但债务利率是百分之七。", "案例B设定", 4,
     "case row B filling in beside row A, only the rate cell changing to seven percent",
     "案例 B 行填在 A 行旁边，只有利率单元格变成百分之七"),
    ("Case C: a three-point-five percent mortgage, where the gap gets much smaller.",
     "案例 C：百分之三点五的房贷，这时的差距会小很多。", "案例C设定", 4,
     "case row C added with a house icon, the rate cell showing three point five",
     "案例 C 行加入，带房屋图标，利率格显示三点五"),
    ("Same cash, three different rates, three completely different answers.",
     "同样的现金，三种利率，三个完全不同的答案。", "对比结论", 4,
     "three result cards side by side, clearly different, host's hooves spread wide",
     "三张结果卡并排，差异明显，主持人双手摊开"),
    ("In the payoff calculator I enter three things: balance, rate, and monthly payment.",
     "在还款计算器里，我只填三样：余额、利率和月供。", "输入说明", 4,
     "three input fields highlighted in the payoff calculator, cursor moving down the list",
     "还款计算器中三个输入框被高亮，光标沿列表下移"),
    ("Two numbers matter most: months to payoff, and total interest paid.",
     "最重要的两个数字是：还清所需月数，以及总利息。", "输出重点", 4,
     "the results panel with two figures circled in green, everything else dimmed",
     "结果面板中两个数字被绿色圈出，其余部分变暗"),
    ("Case A takes about nineteen months and roughly fifteen hundred in interest.",
     "案例 A 大约需要十九个月还清，利息约一千五百美元。", "案例A结果", 4,
     "nineteen months and fifteen hundred dollars appearing under case row A in bold",
     "案例 A 行下方粗体显示十九个月和一千五百美元"),
    ("Now invest that same five hundred instead, at a seven percent assumed return.",
     "现在换成把这五百美元拿去投资，按百分之七的假设回报。", "对照切换", 4,
     "the same five hundred moving from the debt column into an investment column",
     "同样的五百美元从债务列移入投资列"),
    ("You'd end up near eleven thousand, but the card balance is still sitting there.",
     "最终你可能有近一万一千美元，但卡债还一直在那儿。", "两难呈现", 4,
     "a growing investment balance beside an unchanged debt balance, visual tension",
     "增长的投资余额旁边是纹丝不动的债务余额，形成视觉张力"),
    ("And it kept charging twenty-two percent the whole time you were investing.",
     "而且在你投资的整个过程中，它一直在按百分之二十二计费。", "关键揭示", 0,
     "a red interest meter climbing steadily beside the investment chart, host's stern look",
     "投资曲线旁是一路攀升的红色利息计量表，主持人神情严厉"),
    ("That's the comparison people skip. They look at one side only.",
     "这正是大家跳过的对比。他们只看了一边。", "认知纠偏", 0,
     "one half of a balance scale weighted down, the other half ignored",
     "天平一侧被压沉，另一侧被完全忽略"),
    ("Case B is much closer. Seven percent debt against a seven percent assumed return.",
     "案例 B 就接近得多。百分之七的债务对上百分之七的假设回报。", "案例B分析", 4,
     "two nearly equal columns on a chart, the gap between them almost invisible",
     "图表上两根几乎等高的柱子，差距几乎看不见"),
    ("When numbers are that close, the tie-breakers decide it, not the math.",
     "当数字这么接近时，决定结果的是附加因素，而不是算术。", "判断转移", 0,
     "the calculator result shrinking, two tie-breaker icons taking its place",
     "计算器结果缩小，两个附加因素图标取而代之"),
    ("How stable is your income. How much do you value having cash available.",
     "你的收入有多稳定。你有多看重手头有可用现金。", "因素列举", 0,
     "two question cards on screen, host ticking them off one hoof at a time",
     "屏幕上两张问题卡，主持人用手指逐条点数"),
    ("No calculator answers those for you. That part is a judgment call.",
     "没有计算器能替你回答这些。那部分属于个人判断。", "边界说明", 0,
     "closing the calculator window with a calm click, turning to camera",
     "平静地点击关闭计算器窗口，转身面向镜头"),
    ("Case C surprises people. At three-point-five percent, investing often wins on paper.",
     "案例 C 让很多人意外。在百分之三点五的利率下，投资在纸面上常常胜出。", "案例C结果", 4,
     "case row C result showing the investment column ahead, a small surprised icon",
     "案例 C 行结果显示投资栏领先，配一个小小的惊讶图标"),
    ("But on paper assumes you invest every month for decades without stopping.",
     "但「纸面上」假设的是你几十年如一日、每月不间断地投资。", "假设拆解", 0,
     "a long unbroken arrow spanning decades on a timeline, then a hoof breaking it",
     "时间线上一支横跨数十年的完整箭头，随后被一只手打断"),
    ("Most people don't, and that spreadsheet never gets tested in real life.",
     "大多数人做不到，那张表格也就永远不会在现实里被检验。", "现实提醒", 0,
     "the spreadsheet fading to grey, real life icons replacing the formulas",
     "电子表格褪成灰色，现实生活图标取代了公式"),
    ("So the answer isn't a fixed rule. It's a boundary that moves with the rate.",
     "所以答案不是一条固定规则，而是一条随利率移动的边界。", "框架总结", 0,
     "drawing a boundary line on the whiteboard, then sliding it along the rate axis",
     "在白板上画一条边界线，然后沿着利率轴滑动它"),
    ("Above your expected return, paying down debt is usually the safer math.",
     "当利率高于你的预期回报时，还债通常是更稳妥的算法。", "上半规则", 0,
     "the zone above the boundary line shaded green and labeled PAY DOWN",
     "边界线上方区域被涂成绿色并标注 PAY DOWN"),
    ("Below it, investing often wins, but only with genuine discipline.",
     "低于它时，投资常常占优，但前提是你真的有纪律。", "下半规则", 0,
     "the zone below the line shaded blue, labeled INVEST, with a discipline footnote",
     "线下方区域涂成蓝色，标注 INVEST，附一行纪律说明"),

    # ============ 章节 6 · 三个陷阱（3:45–5:00）============
    ("Three traps make smart people ignore everything we just calculated.",
     "有三个陷阱，会让聪明人忽略我们刚刚算出的所有结果。", "陷阱预告", 5,
     "three warning cards flipping over on screen one by one, host's expression turning serious",
     "三张警示卡在屏幕上依次翻面，主持人表情转为严肃"),
    ("Trap one is a zero percent promotional offer.",
     "第一个陷阱是百分之零的促销利率。", "陷阱一", 5,
     "a glossy credit offer with a giant 0% headline, host raising a cautioning hoof",
     "一张印着巨大 0% 标题的信用卡 offer，主持人举起警示的手指"),
    ("The offer hides three fields: the end date, the transfer fee, and the rate after.",
     "这份 offer 里藏着三个字段：截止日期、转账手续费，以及之后的利率。", "字段列举", 5,
     "three fields on the offer document highlighted in different colors",
     "offer 文件上三个字段被不同颜色高亮"),
    ("If the promotion ends before the balance is gone, the math changes completely.",
     "如果促销在余额还清前就结束，整个算法会彻底改变。", "后果说明", 5,
     "a timeline showing the promo ending while a balance bar is still half full",
     "时间线显示促销结束时，余额进度条仍有一半"),
    ("Trap two is the plan to invest the gains and use them to pay the card.",
     "第二个陷阱，是先投资拿收益、再用收益去还卡的计划。", "陷阱二", 5,
     "a circular arrow between an investment chart and a credit card, host tracing it",
     "投资曲线与信用卡之间的循环箭头，主持人用手指描着它"),
    ("That only works if the market cooperates, and sometimes it doesn't for years.",
     "这只有在市场配合时才成立，而有时市场会连续几年不配合。", "条件揭示", 0,
     "a market line flatlining across several years, host's sober expression",
     "市场曲线连续几年走平，主持人神情冷静"),
    ("You're borrowing at a certain rate to chase a return that isn't certain.",
     "你是在以确定的利率借钱，去追逐一个并不确定的回报。", "风险本质", 0,
     "a solid red cost block outweighing a translucent question-mark return block",
     "实心红色成本方块压过半透明的问号回报方块"),
    ("Trap three is holding a huge emergency fund while the card compounds.",
     "第三个陷阱，是在信用卡不断复利的同时，还握着一大笔应急金。", "陷阱三", 5,
     "a large savings balance beside a compounding debt bar, arrows of unequal size",
     "大额储蓄余额旁是不断复利的债务柱，两支箭头大小悬殊"),
    ("I'm not telling you to drain your cash. That's how people get wrecked.",
     "我不是让你把现金清空。那样做只会让人被拖垮。", "风险澄清", 0,
     "both palms up in a calming gesture, reassuring steady gaze",
     "双掌心向上做出安抚手势，目光平稳令人安心"),
    ("Keep a basic buffer, then compare the yield on the extra cash with your APR.",
     "先留一笔基本缓冲金，再把多余现金的收益率和你的 APR 做比较。", "方法给出", 5,
     "a cash buffer block staying in place while an excess cash block moves to compare",
     "现金缓冲块留在原地，多余现金块移过去做比较"),
    ("If your savings earn four percent and your card charges twenty-two, that gap is real.",
     "如果你的储蓄赚百分之四，而信用卡收百分之二十二，这个差距是真实存在的。", "数字对比", 5,
     "4% and 22% side by side with a wide gap arrow between them",
     "4% 与 22% 并排，中间是宽大的差距箭头"),
    ("The useful part isn't the rule. It's knowing which field to look at.",
     "真正有用的不是那条规则，而是知道该看哪一个字段。", "方法提炼", 0,
     "tapping a document field with one hoof, then looking up at camera",
     "用一根手指轻点文件字段，然后抬头看向镜头"),
    ("Every trap lives in a specific line on a specific document.",
     "每一个陷阱，都藏在某份文件的某一行里。", "定位原则", 5,
     "three documents lined up, each with one line glowing red",
     "三份文件并排排列，每份都有一行泛着红光"),
    ("On a promotional offer, find where the regular rate starts.",
     "在促销 offer 上，找到常规利率从哪儿开始生效。", "实操指引", 5,
     "the regular rate line circled on a promotional offer document",
     "促销 offer 文件上常规利率那行被圈出"),
    ("On a savings account, find the annual percentage yield.",
     "在储蓄账户上，找到年化收益率 APY。", "实操指引", 5,
     "the APY field highlighted on a savings account summary screen",
     "储蓄账户概览页上 APY 字段被高亮"),
    ("On a statement, find the APR, not just the minimum payment.",
     "在账单上，找到 APR，而不只是最低还款额。", "实操指引", 5,
     "the APR line circled in green while the minimum payment is dimmed",
     "APR 一行被绿色圈出，最低还款额则被淡化"),
    ("A good finance video teaches you how to read a document.",
     "一条好的财经视频，教你怎么读懂一份文件。", "价值主张", 0,
     "holding a document up beside its face, meeting the camera directly",
     "把一份文件举在脸旁，直视镜头"),
    ("It doesn't just hand you a conclusion to memorize.",
     "而不只是丢给你一个需要死记的结论。", "对比收尾", 0,
     "setting a flashcard-style conclusion card aside on the desk, calm smile",
     "把一张抽认卡式的结论卡放到桌边，平静微笑"),
]
