# -*- coding: utf-8 -*-
# 金融包 · 章节 1–4（Hook / 三问测试 / 痛点代入 / 官方数据与计算器）
# 每句元组：(en, zh, viz, demo_id, img_en, img_zh)
# demo_id: 0=不需要实操，1..8=对应实操卡编号

LINES = [
    # ============ 章节 1 · Hook（0:00–0:15）============
    ("Before you invest another dollar, open your credit-card statement and find one number.",
     "在你再投一美元之前，先打开信用卡账单，找到其中一个数字。", "指令开场", 1,
     "holding a redacted credit-card statement, one hoof circling the APR field, calm serious gaze",
     "手持打码的信用卡账单，一根手指圈住 APR 字段，平静而严肃的目光"),
    ("If that APR is twenty-two percent, the order of your decisions matters more than the amount.",
     "如果那个 APR 是百分之二十二，那么你做决定的顺序，比金额本身更重要。", "结论抛出", 1,
     "a giant red 22% figure behind him on a dark board, host gesturing toward the order of two arrows",
     "身后深色板子上是巨大的红色 22%，主持人指向两支箭头的先后顺序"),
    ("I'll show you why in under two minutes, using three numbers you already have.",
     "我用不到两分钟讲清楚原因，而且只用你已经有的三个数字。", "承诺时限", 0,
     "three blank number cards on screen, host holding up a timer with two minutes",
     "屏幕上三张空白数字卡，主持人举起显示两分钟的计时器"),
    ("And one retirement-account exception that can flip the entire answer.",
     "还有一个退休账户的例外，它能把整个答案翻转过来。", "悬念预告", 0,
     "a retirement account icon appearing at the edge of the frame, partially revealed, intriguing",
     "退休账户图标出现在画面边缘，只露出一半，引人好奇"),

    # ============ 章节 2 · 三问测试（0:15–0:30）============
    ("Question one: what is your highest interest rate right now?",
     "第一个问题：你现在最高的利率是多少？", "提问一", 2,
     "writing question one on a whiteboard, marker hovering, attentive expression",
     "在白板上写下第一个问题，马克笔悬停，神情专注"),
    ("Question two: how much extra cash can you put toward this every month?",
     "第二个问题：你每个月能多拿出多少现金来解决它？", "提问二", 2,
     "a monthly budget row highlighted on screen, host tapping the surplus figure",
     "屏幕上高亮一行月度预算，主持人轻点结余数字"),
    ("Question three: does your employer match any of your retirement contributions?",
     "第三个问题：你的公司有没有为你的退休账户缴款做配比？", "提问三", 2,
     "a pay stub with an employer match line highlighted, host leaning in to point",
     "工资单上雇主配比一行被高亮，主持人身体前倾指点"),
    ("Write those three down. Everything after this is just arithmetic.",
     "把这三个数字写下来。后面的内容就只是算术了。", "流程预告", 2,
     "three filled answer boxes on a clean worksheet, host sliding it toward camera",
     "干净工作表上三个已填好的答案框，主持人把它推向镜头"),

    # ============ 章节 3 · 痛点代入（0:30–1:25）============
    ("Here's why this feels so confusing, and it's not because you're bad with money.",
     "这件事之所以让人困惑，并不是因为你不擅长管钱。", "共情开场", 0,
     "open relaxed posture, slight sympathetic smile, warm desk lamp",
     "放松开放的姿态，略带同情的微笑，温暖的台灯"),
    ("Your investment app shows a green number every time the market rises.",
     "你的投资 App 在市场上涨时，总会给你一个绿色的数字。", "场景对比", 0,
     "a phone screen glowing green with an upward chart, host holding it at an angle",
     "手机屏幕泛着绿色上涨曲线，主持人斜握着手机"),
    ("Your credit-card statement hides the damage inside a minimum payment.",
     "而你的信用卡账单，把损失藏在最低还款额里。", "隐藏成本", 0,
     "the minimum payment line circled on a statement, the interest line barely visible",
     "账单上最低还款额一行被圈出，利息那行几乎看不见"),
    ("One account is loud and rewarding. The other one is quiet and expensive.",
     "一个账户喧闹又给你正反馈，另一个安静却昂贵。", "对比提炼", 0,
     "two accounts side by side, one bright and noisy, one dim with a slow drip",
     "两个账户并排，一个明亮喧闹，一个昏暗且在缓慢滴漏"),
    ("Let's put real numbers on it. Say you owe eight thousand at twenty-two percent.",
     "我们放上真实数字。假设你欠八千美元，利率百分之二十二。", "数字设定", 0,
     "writing 8000 and 22% on the whiteboard, turning back to camera",
     "在白板上写下 8000 和 22%，转身面向镜头"),
    ("Roughly, that balance charges about one thousand seven hundred sixty dollars a year.",
     "粗略计算，这笔余额一年大约产生一千七百六十美元的利息。", "成本披露", 0,
     "a calculator showing 8000 times 0.22, the result highlighted in red",
     "计算器显示 8000 乘以 0.22，结果被红色高亮"),
    ("Now take the same eight thousand and assume a seven percent long-term return, after inflation.",
     "现在把同样的八千美元，按扣除通胀后长期百分之七的回报来假设。", "假设切换", 0,
     "the same 8000 figure moving to a second column marked seven percent after inflation",
     "同一个 8000 移到标注「扣除通胀后 7%」的第二栏"),
    ("That's about five hundred sixty dollars of expected growth, not guaranteed.",
     "那大约是五百六十美元的预期增长，而且并不保证。", "预期标注", 0,
     "560 highlighted in amber with the words EXPECTED, NOT GUARANTEED beneath it",
     "560 用琥珀色高亮，下方写着 EXPECTED, NOT GUARANTEED"),
    ("In a bad year, that growth can be negative. The interest charge never takes a year off.",
     "行情差的年份，这个增长可能是负数。但利息一年都不会停。", "确定对比", 0,
     "a jagged market line dipping below zero beside a steady red interest line climbing",
     "锯齿状市场曲线跌破零线，旁边是稳步上升的红色利息线"),
    ("The mistake is treating those two numbers as if they carry the same certainty.",
     "真正的错误，是把这两个数字当成同样确定。", "认知纠偏", 0,
     "both hooves weighing two invisible objects, one steady and one wobbling",
     "双蹄掂量两个无形物体，一个平稳一个摇晃"),
    ("Paying down the card removes a known cost you are already paying.",
     "还掉卡债，是在消除一个你已经在付的确定成本。", "确定性说明", 0,
     "a red cost block being lifted off a balance scale, the scale rising",
     "一块红色成本方块被从天平上取走，天平上扬"),
    ("Investing accepts an uncertain result you only get if markets cooperate.",
     "而投资，是接受一个只有市场配合才会出现的不确定结果。", "不确定性说明", 0,
     "a question mark hovering over a projected growth curve, host's calm expression",
     "问号悬浮在预测增长曲线上方，主持人神情平静"),
    ("That doesn't mean every debt outranks every investment. It means you compare rates, taxes, and time.",
     "这不代表所有债务都排在所有投资前面，而是你要比较利率、税务和时间。", "框架提出", 0,
     "three comparison columns drawn on the whiteboard: rate, tax, time horizon",
     "白板上画出三栏对比：利率、税务、时间期限"),

    # ============ 章节 4 · 官方数据与计算器（1:25–2:30）============
    ("So let's stop repeating slogans and go look at the actual source.",
     "所以我们别再重复口号了，直接去看真正的来源。", "转入实证", 3,
     "turning to the monitor with a browser open, sleeves straightened, focused",
     "转向已打开浏览器的显示器，捋直袖口，神情专注"),
    ("Open the Federal Reserve's consumer credit release, the G.19 report.",
     "打开美联储的消费者信贷报告，也就是 G.19。", "来源指引", 3,
     "the G.19 page loading in the browser, the URL bar clearly visible",
     "浏览器中加载 G.19 页面，地址栏清晰可见"),
    ("You'll see two different credit-card rates on that page, and the difference matters.",
     "你会在这个页面看到两个不同的信用卡利率，而这个差别很关键。", "口径提示", 3,
     "two rate rows on screen, host's cursor moving slowly between them",
     "屏幕上两行利率数据，主持人的光标在两者间缓慢移动"),
    ("One is the average across all accounts, including people who pay in full every month.",
     "一个是所有账户的平均值，包含那些每月全额还款的人。", "口径解释", 3,
     "a wide crowd of account icons, most marked PAID IN FULL in green",
     "一大片账户图标，多数被绿色标注为全额还款"),
    ("The other is the rate on accounts actually carrying a balance and being charged interest.",
     "另一个，是真正背着余额、正在被计息的账户利率。", "口径解释", 3,
     "a smaller set of account icons highlighted in red, marked ASSESSED INTEREST",
     "一小部分账户图标被红色高亮，标注为正在计息"),
    ("If you carry a balance, that second figure is the one that describes your life.",
     "如果你背着余额，那么第二个数字才是描述你处境的那个。", "对号入座", 3,
     "the assessed interest figure enlarging on screen, host nodding at camera",
     "正在计息的数字在屏幕上放大，主持人对镜头点头"),
    ("Check the publication date on that page, because these rates move over time.",
     "务必看一下那个页面的发布日期，因为这些利率会随时间变化。", "时效提醒", 3,
     "the release date field circled on the page, a small calendar icon beside it",
     "页面上的发布日期字段被圈出，旁边一个小日历图标"),
    ("I open a compound interest calculator next. There are four boxes to fill in.",
     "接着我打开复利计算器。一共有四个输入框要填。", "工具切换", 3,
     "the compound interest calculator loading, four empty input fields visible",
     "复利计算器加载完成，四个空白输入框清晰可见"),
    ("Starting balance. Monthly contribution. Assumed return. Number of years.",
     "初始金额、每月投入、假设回报、以及年数。", "字段列举", 3,
     "the four field labels appearing in sequence as the cursor passes each one",
     "四个字段标签随光标经过依次出现"),
    ("Notice the word assumed. Nothing on this page is a promise or a forecast.",
     "注意「假设」这个词。这一页上没有任何东西是承诺或预测。", "措辞强调", 3,
     "the word ASSUMED magnified on screen, host raising one hoof",
     "屏幕上 ASSUMED 一词被放大，主持人竖起一根手指"),
    ("Type in that markets return ten percent, and you've quietly written fiction.",
     "如果你直接填市场回报百分之十，那你其实是在悄悄写小说。", "常见错误", 3,
     "a red warning appearing beside a ten percent input, host shaking its head",
     "在 10% 输入框旁出现红色警告，主持人摇头"),
    ("Keep the inputs beside the result, so anyone can check the arithmetic later.",
     "把输入参数和结果放在一起，这样任何人之后都能复核这笔账。", "可复算要求", 3,
     "a screenshot showing both the input panel and the output panel side by side",
     "截图同时显示输入面板和输出面板并排"),
    ("A viewer should be able to swap in their own numbers and check your work.",
     "观众应该能换成自己的数字，去复核你的计算。", "验证原则", 0,
     "two calculators side by side with different numbers, both producing visible results",
     "两台并排计算器填着不同数字，都显示出可见结果"),
    ("That's the difference between a finance video and a finance opinion.",
     "这就是财经视频和财经观点的区别。", "金句点题", 0,
     "steady look into camera, one hoof resting flat on the desk",
     "沉稳地看向镜头，一只手平放在桌面上"),
    ("Now let's run three households through the exact same monthly cash.",
     "现在我们用同样的月现金流，跑三个家庭案例。", "转入案例", 4,
     "a three-row case table appearing, monthly cash column identical in all three rows",
     "出现三行案例表，三行的月现金流列完全相同"),
]
