# -*- coding: utf-8 -*-
# 金融包 · 章节 7–8（401(k) 配比例外 / 金句 + CTA）
# 每句元组：(en, zh, viz, demo_id, img_en, img_zh)

LINES = [
    # ============ 章节 7 · 401(k) 配比例外（5:00–6:15）============
    ("Now the one exception that can override everything above: an employer retirement match.",
     "现在讲唯一能推翻上面所有结论的例外：雇主的退休账户配比。", "例外引入", 6,
     "a retirement plan document sliding onto the desk, host's expression brightening slightly",
     "一份退休计划文件滑到桌上，主持人神情略微一亮"),
    ("Open your plan document and find the exact matching formula.",
     "打开你的计划文件，找到准确的配比公式。", "操作指引", 6,
     "the plan document open on screen, cursor scrolling toward a match section",
     "计划文件在屏幕上打开，光标滚向配比章节"),
    ("A common one is fifty cents per dollar, up to six percent of your pay.",
     "常见的一种是：你每存一美元，公司配五角，上限为工资的百分之六。", "公式示例", 6,
     "the match formula highlighted on the page, fifty cents and six percent both glowing",
     "页面上的配比公式被高亮，五角与百分之六同时发光"),
    ("That is not a market return. It is money added to your account immediately.",
     "那不是市场回报，而是立刻加进你账户的钱。", "本质澄清", 6,
     "an employer contribution block landing on a balance stack, no market arrow involved",
     "雇主缴款方块落到余额堆上，完全没有市场曲线参与"),
    ("No market has to cooperate for that contribution to appear.",
     "这笔缴款的出现，不需要市场配合一分一毫。", "确定性强调", 0,
     "host's hoof blocking a market chart, while the contribution stays solid",
     "主持人的手挡住市场走势图，而那笔缴款依然稳固"),
    ("So the order changes. Let me draw it, because the sequence is the whole point.",
     "所以顺序要改。我把它画出来，因为顺序本身就是重点。", "转入顺序", 6,
     "picking up a marker in front of a blank whiteboard, ready to write",
     "在空白白板前拿起马克笔，准备书写"),
    ("Step one: a basic cash buffer, so a flat tire doesn't become new debt.",
     "第一步：留一笔基本现金缓冲，免得一次修车变成新的债务。", "步骤一", 6,
     "writing step one on the board beside a small shield icon",
     "在白板上写下第一步，旁边是一个小盾牌图标"),
    ("Step two: contribute enough to capture the full employer match.",
     "第二步：缴到能拿满雇主配比的额度。", "步骤二", 6,
     "step two appearing, with a match coin icon filling to one hundred percent",
     "第二步出现，配比金币图标填充到百分之百"),
    ("Step three: attack any high-interest balance, because that cost is certain.",
     "第三步：处理任何高息余额，因为那笔成本是确定的。", "步骤三", 6,
     "step three beside a red high-rate debt bar being pushed down",
     "第三步旁是一根被压下去的红色高息债务柱"),
    ("Step four: handle lower-rate debt based on the spread and your own risk.",
     "第四步：根据利差和你的风险承受，处理低息债务。", "步骤四", 6,
     "step four beside a narrow gap between two moderate rate bars",
     "第四步旁是两根中等利率柱之间的狭窄差距"),
    ("Step five: invest what's left, consistently and without drama.",
     "第五步：把剩下的钱拿去投资，保持规律，别折腾。", "步骤五", 6,
     "step five beside a steady rising contribution line, calm and unglamorous",
     "第五步旁是平稳上升的投入线，冷静而朴实"),
    ("Notice what isn't on this list: guessing, timing, and clever shortcuts.",
     "注意这份清单上没有的东西：猜测、择时和小聪明。", "反向强调", 0,
     "three crossed-out words on the board: guessing, timing, shortcuts",
     "白板上三个被划掉的词：猜测、择时、捷径"),
    ("If your plan has vesting rules, read them before you count that money as yours.",
     "如果你的计划有归属期规则，在把那笔钱算作自己的之前先读懂它。", "归属提醒", 6,
     "a vesting schedule table with a gradual ownership curve, cursor tracing it",
     "归属期进度表配一条渐进的所有权曲线，光标沿曲线移动"),
    ("If it has fees, find the expense line and see what you're actually paying.",
     "如果有费用，找到费用那一行，看清楚你实际付了多少。", "费用提醒", 6,
     "an expense ratio line highlighted on a fund summary page",
     "基金概览页上被高亮的费用率一行"),
    ("And if the formula differs from my example, use yours, not mine.",
     "如果你的公式和我的示例不同，请用你自己的，不要用我的。", "个性化强调", 6,
     "two different match formulas side by side, the viewer's own one marked USE THIS",
     "两个不同的配比公式并排，属于观众自己的那份标注 USE THIS"),
    ("This is not a prescription. It's a checklist for reading your own plan.",
     "这不是一张处方，而是一份帮你读懂自己计划的清单。", "定位澄清", 0,
     "open hoof toward camera, calm and measured expression",
     "掌心朝向镜头，冷静而有分寸的表情"),
    ("If the document is unclear, that's your answer: it's unclear.",
     "如果文件写得不清楚，那这就是你的答案：它不清楚。", "诚实边界", 6,
     "a blurry document section with a question mark, host shrugging honestly",
     "文件某段模糊不清并打着问号，主持人坦诚地耸肩"),
    ("Call the plan administrator instead of guessing at a formula.",
     "去问计划管理员，而不是自己猜一个公式。", "行动建议", 6,
     "a phone icon beside the plan document, host nodding as if agreeing with himself",
     "计划文件旁是一个电话图标，主持人像是认同自己般点头"),

    # ============ 章节 8 · 金句 + CTA（6:15–7:00）============
    ("Here's the one sentence worth writing down tonight.",
     "有句话值得你今晚就写下来。", "金句预告", 7,
     "holding a pen over a notepad, evening desk lamp glow, focused calm",
     "手持钢笔悬在记事本上，傍晚台灯的光晕，专注而平静"),
    ("Paying off a high-interest balance is not anti-investing.",
     "还清高息债务，并不等于反对投资。", "观点澄清", 0,
     "a debt bar shrinking beside an investment chart that keeps growing, no conflict",
     "债务柱在缩小，旁边投资曲线持续增长，二者并不冲突"),
    ("It's removing a known drag before you take an uncertain risk.",
     "它是在承担不确定风险之前，先移除一个确定的拖累。", "金句落定", 0,
     "a heavy chain falling away from an anchored boat that then sails freely",
     "沉重的锁链从停泊的船上脱落，随后小船自由航行"),
    ("Write down your rate, your monthly cash, and your employer match.",
     "写下你的利率、每月可用现金，以及雇主配比。", "行动指令", 7,
     "three lines being filled in on a worksheet, pen moving steadily",
     "工作表上三行正在被填写，笔尖稳定移动"),
    ("Run them through the three-question sheet linked in the description.",
     "把它们套进简介里那张三问表。", "资源指引", 7,
     "the worksheet on screen with a small link icon pointing to the description area",
     "屏幕上的工作表配一个小链接图标，指向简介区域"),
    ("Save your assumptions right next to your result, not somewhere in your head.",
     "把你的假设和结果存在一起，而不是只存在于脑子里。", "可复算强调", 7,
     "an assumptions block physically pinned beside a result block on screen",
     "假设区块被牢牢钉在结果区块旁边"),
    ("Do not copy my example and call it a plan. It was never built for you.",
     "别把我的示例照抄成你的计划。它从来不是为你设计的。", "免责提醒", 0,
     "pushing a sample sheet aside and sliding a blank one forward",
     "把示例表推到一边，把一张空白表推到前面"),
    ("If you want the next calculator walkthrough, comment the word math.",
     "如果你想看下一期计算器实操，在评论区打 MATH。", "评论互动", 8,
     "pointing downward toward the comments, a speech bubble showing the word MATH",
     "指向下方评论区，气泡里显示 MATH 一词"),
    ("Next week I'll show which balance to attack when you have three of them.",
     "下周我会讲：当你同时有三笔欠款时，先攻哪一笔。", "下期预告", 0,
     "three debt bars of different heights, a marker question mark above the smallest",
     "三根高度不同的债务柱，问号标记悬在最小的一根上方"),
    ("Subscribe, and bring your own numbers when you come back.",
     "订阅频道，下次回来时带上你自己的数字。", "订阅引导", 8,
     "a subscribe prompt beside a worksheet with blank fields waiting to be filled",
     "订阅提示旁是一张字段空白、等待填写的工作表"),
    ("The goal isn't a louder opinion. It's a decision you can reproduce.",
     "我们的目标不是更响亮的观点，而是一个你能自己复算的决定。", "收尾金句", 0,
     "steady gaze into camera, both hooves resting on the closed plan document",
     "沉稳地看向镜头，双蹄放在已合上的计划文件上"),
    ("Run the numbers. Then decide. I'll see you next week.",
     "先算数字，再做决定。我们下周见。", "行动收尾", 0,
     "final wide shot in the study, closing the notebook, warm lamp light fading slightly",
     "书房里的最后全景镜头，合上笔记本，温暖的灯光微微暗下"),
]
