# -*- coding: utf-8 -*-
# 金融包 · 实操执行卡（8 张）
# 每张卡：id / title / window / software / shots / steps[{do, see}] / verify / pitfalls / audio

DEMOS = [
    {
        "id": 1,
        "title": "从账单里找出真正的 APR（全片第一个动作）",
        "window": "00:00–00:15",
        "software": "银行 App 或账单 PDF（必须打码）",
        "shots": "先主机位手持实体账单 2 秒建立真实感 → 切屏幕录制全屏 → 用矩形标注工具圈住 APR。不加速。",
        "steps": [
            {"do": "打开账单 PDF，先把姓名、卡号、地址、交易明细全部涂黑或裁掉",
             "see": "画面上只剩结构性字段，不含任何个人识别信息"},
            {"do": "放大到「Interest Charge Calculation」或「APR」区块",
             "see": "出现 Purchase APR、Balance Transfer APR、Cash Advance APR 等多行"},
            {"do": "用红色矩形圈住 Purchase APR（消费 APR），旁边打标注 THIS ONE",
             "see": "只有消费 APR 被高亮，避免和现金预借 APR 混淆"},
            {"do": "把该数字抄进屏幕右侧的三问表第一格",
             "see": "三问表第一行「Highest APR」被填上"},
            {"do": "在该数字旁加一行小字：示例投资回报为假设，不是保证",
             "see": "屏幕角落出现免责小字，字号要够大能看清"},
        ],
        "verify": "观众知道自己该打开账单找哪个字段，而不是只听到一个 22% 的口号。",
        "pitfalls": [
            "绝不能露出真实卡号、姓名、地址或消费明细——这是隐私红线。",
            "不要把「现金预借 APR」当成消费 APR，两者常常不同。",
            "画面上必须同时出现「APR 是确定成本」与「投资回报是假设」的对照标注。",
        ],
        "audio": "口播说 find one number 时，红框正好圈住 APR；说 twenty-two percent 时该数字被放大。",
    },
    {
        "id": 2,
        "title": "建立三问测试表（观众可以暂停跟做）",
        "window": "00:15–00:30",
        "software": "Google Sheets 或白板",
        "shots": "全屏屏幕录制建表 → 切主机位在白板上手写三问 → 回屏幕。建表过程 2 倍速。",
        "steps": [
            {"do": "新建表格，三行：Highest APR / Monthly extra cash / Employer match",
             "see": "三行标签，右侧三列分别为 Your number、Example、Notes"},
            {"do": "在 Example 列填入示例值（22% / $500 / 50% up to 6%），Your number 列留空",
             "see": "示例列有数字，观众列空着"},
            {"do": "在 Notes 列标注每个数字的来源：账单 / 预算表 / 计划文件",
             "see": "每个数字旁边都有来源字段，养成可追溯习惯"},
            {"do": "把表格冻结首行并保存为可复制模板",
             "see": "表格标题栏固定，滚动时仍可见"},
            {"do": "切主机位，在白板上手写同样三个问题",
             "see": "白板三问与屏幕表格一致，方便观众截图"},
        ],
        "verify": "观众能暂停视频，把自己的三个数字填进 Your number 列。",
        "pitfalls": [
            "不要在示例列填看起来像「真实客户」的数字，用明显是示例的圆整值。",
            "三问表必须可复制可下载，只在视频里念一遍等于没给。",
        ],
        "audio": "口播问三个问题时，白板上正好写完三行；说 write those three down 时切回表格。",
    },
    {
        "id": 3,
        "title": "打开官方数据页与复利计算器（建立可复核性）",
        "window": "01:25–02:30",
        "software": "浏览器（Federal Reserve G.19）+ Investor.gov 复利计算器",
        "shots": "全屏屏幕录制，地址栏必须可见。滚到利率那一行时不加速，并停留 2 秒。",
        "steps": [
            {"do": "浏览器打开 federalreserve.gov 的 G.19 Consumer Credit 页面，展示完整 URL",
             "see": "地址栏清晰可见，页面标题为 Consumer Credit - G.19"},
            {"do": "向下滚动到 Credit Card Plans 表格，找到两行不同的利率",
             "see": "出现 All accounts 与 Accounts assessed interest 两个口径"},
            {"do": "用黄色高亮 Accounts assessed interest 那一行",
             "see": "只有计息账户利率被高亮，旁边标注 USE THIS IF YOU CARRY A BALANCE"},
            {"do": "圈出页面上的发布日期 / 数据月份",
             "see": "日期字段被圈出，提醒观众利率会变"},
            {"do": "新标签页打开 Investor.gov 的 Compound Interest Calculator",
             "see": "计算器页面加载，四个输入框可见"},
            {"do": "依次填入：Starting balance、Monthly contribution、Assumed return、Years",
             "see": "四个框都有示例值，光标逐格移动"},
            {"do": "在 Assumed return 旁加红色批注：assumption, not a forecast",
             "see": "出现警告标注，明确这不是预测"},
            {"do": "对输入面板和结果面板一起截图，保存在表格旁",
             "see": "输入与结果并排出现在同一张截图里"},
        ],
        "verify": "观众能看到来源 URL、利率口径、发布日期，并且能自己换数字复算。",
        "pitfalls": [
            "G.19 的两个口径不能混用——对背余额的人要用计息账户口径。",
            "不要把回报率写成「市场会涨 10%」，那是预测不是假设。",
            "发布日期必须入镜，否则观众会以为这是永久有效的数字。",
            "发布前必须回官网确认当前值；视频里的数字只是录制当天的快照。",
        ],
        "audio": "口播说 two different rates 时画面在两个口径间移动；说 note the publication date 时圈出日期。",
    },
    {
        "id": 4,
        "title": "三案例计算器对比（只改利率，其他不动）",
        "window": "02:30–03:45",
        "software": "债务还款计算器（Bankrate 等）+ Google Sheets",
        "shots": "全屏屏幕录制。三个案例连续跑，每次只改 APR 一格；改之前先把上一次结果留在屏幕上做对照。",
        "steps": [
            {"do": "打开还款计算器，建立 Case A：余额 8000、APR 22%、月供 500",
             "see": "结果出现：约 19 个月还清，总利息约 1500"},
            {"do": "把结果抄进表格 Case A 行，截图存档",
             "see": "表格第一行填入 months 与 total interest"},
            {"do": "只把 APR 改成 7%，余额和月供保持不动，重新计算",
             "see": "还清月数与总利息明显下降——直观展示利率的作用"},
            {"do": "再把 APR 改成 3.5%，保持余额与月供不变",
             "see": "数字再次变化，差距进一步缩小"},
            {"do": "在同一张表里新增「若改为投资」列，填入同样的月供与假设回报",
             "see": "出现债务方案与投资方案的并排对比"},
            {"do": "在表头写一行假设说明：不含税费、不含余额变化、回报为假设",
             "see": "表头出现完整的假设清单"},
        ],
        "verify": "三次计算里只有 APR 在变，余额和月供始终不变；观众能看出是哪一个变量改变了结果。",
        "pitfalls": [
            "三个案例必须只改一个变量，否则对比不成立，也是最常见的作弊手法。",
            "表格里必须写清假设，不能让观众以为这是预测。",
            "不要用「投资一定赚」的口吻，要说 expected, not guaranteed。",
        ],
        "audio": "口播说 change only the rate 时，画面确实只改了 APR 一格；这句话要和鼠标动作同步。",
    },
    {
        "id": 5,
        "title": "在三份文件上圈出真正会改变计算的字段",
        "window": "03:45–05:00",
        "software": "信用卡 offer PDF + 账单 PDF + 储蓄账户页面（全部打码）",
        "shots": "三份文件依次全屏展示，每份停留 4–6 秒。红框标陷阱字段，绿框标必须核对的字段。",
        "steps": [
            {"do": "打开 0% 促销 offer，用红框圈出促销截止日期",
             "see": "截止日期被红框圈出"},
            {"do": "继续圈出 balance transfer fee（通常为转账额的百分比）",
             "see": "手续费字段被红框圈出"},
            {"do": "圈出促销结束后的 regular APR",
             "see": "常规利率被红框圈出，这是最容易被忽略的一项"},
            {"do": "切换到账单，用绿框标出 Purchase APR",
             "see": "APR 被绿框标出，与红框的陷阱字段形成对比"},
            {"do": "切换到储蓄账户页面，用绿框标出 APY",
             "see": "APY 字段被标出"},
            {"do": "把三个陷阱字段与三问表/计算表对应起来，说明各自影响哪一格",
             "see": "屏幕一侧出现字段与表格单元格的连线"},
        ],
        "verify": "观众学会在文件上找字段，而不只是记住「0% 有坑」这种结论。",
        "pitfalls": [
            "所有文件必须打码，不能出现真实账号、姓名或余额。",
            "只说「有坑」不给字段位置，等于没讲——必须指到具体那一行。",
            "不同的卡片、不同的州规则不同，不能把一份 offer 的条款套给所有人。",
        ],
        "audio": "口播说 find where the regular rate starts 时，红框正好落在常规利率那一行。",
    },
    {
        "id": 6,
        "title": "从 401(k) 计划文件里找到真实的 match 公式",
        "window": "05:00–06:15",
        "software": "401(k) plan document PDF 或工资单（示例或打码）",
        "shots": "全屏屏幕录制 PDF。滚到 match 章节时不加速；找不到时如实停顿。",
        "steps": [
            {"do": "打开计划文件（或示例文件），滚动到 Employer Contributions / Match 章节",
             "see": "标题为 Employer Matching Contribution 的章节出现在页面上"},
            {"do": "高亮匹配公式（如 50% of the first 6% of eligible pay）",
             "see": "公式被黄色高亮，两个关键数字都可见"},
            {"do": "在旁边新建计算：月薪 × 6% = 需自缴金额；公司配一半",
             "see": "出现一个小算式，算出拿满配比需要缴多少"},
            {"do": "向下找 Vesting schedule，展示归属进度表",
             "see": "出现归属期曲线或表格，说明公司缴款何时真正属于你"},
            {"do": "查找费用相关章节（expense ratio / admin fee）并高亮",
             "see": "费用行被高亮，提醒这是实际成本"},
            {"do": "若文档里某项确实没写清楚，停下来如实说明并提示联系管理员",
             "see": "主持人面对镜头说明「这里文件没写清」，不猜数字"},
            {"do": "在白板上按顺序写下：buffer → match → high-rate debt → low-rate debt → invest",
             "see": "白板上出现五步顺序图"},
        ],
        "verify": "观众知道要读自己的计划文件，而不是照抄视频里的示例公式。",
        "pitfalls": [
            "绝不能把示例公式说成「标准配比」——每个计划都不同。",
            "归属期和费用必须提，漏掉会让观众高估这笔钱。",
            "看不懂就直说看不懂，不要凭印象编一个公式填进去。",
        ],
        "audio": "口播说 if the formula differs, use yours 时，画面展示两个不同公式并标注 USE THIS。",
    },
    {
        "id": 7,
        "title": "三问表收口：把假设和结果存在一起",
        "window": "06:15–06:35",
        "software": "Google Sheets（承接第 2 张卡的表）",
        "shots": "全屏屏幕录制，动作放慢。展示「假设区块」与「结果区块」被并排放置。",
        "steps": [
            {"do": "回到三问表，把 Your number 三格留给观众填，Example 三格保留示例值",
             "see": "两列并存，示例与观众字段区分清楚"},
            {"do": "在表格右侧新增 Assumptions 区块，列出回报率、通胀、时间、税费处理",
             "see": "假设区块四项，每项一行"},
            {"do": "把 Assumptions 区块与结果区块并排冻结，保证滚动时始终同屏",
             "see": "两个区块固定在同一视图内"},
            {"do": "在底部加一行免责说明：教育演示，非个别投资建议",
             "see": "表格底部出现免责行"},
            {"do": "把官方来源链接贴进表格的 Sources 区",
             "see": "Federal Reserve、NY Fed、Investor.gov 等链接可见"},
        ],
        "verify": "观众拿到的不是一张只有结论的表，而是「数字 + 假设 + 来源」完整一套。",
        "pitfalls": [
            "只存结果不存假设，几周后连自己都不知道当时怎么算出来的。",
            "免责说明不能省，也不能小到看不见。",
        ],
        "audio": "口播说 save your assumptions next to your result 时，两个区块正好并排出现。",
    },
    {
        "id": 8,
        "title": "CTA 落地：评论互动与下期预告",
        "window": "06:35–07:00",
        "software": "YouTube 后台 / 评论区示意图",
        "shots": "主机位中近景为主，屏幕只占一小块。语气平稳，不做夸张表情。",
        "steps": [
            {"do": "指向下方评论区，展示一个写着 MATH 的气泡",
             "see": "评论框里出现 MATH 一词"},
            {"do": "展示下期题目：三笔欠款、每月只够多还一笔时先攻哪笔",
             "see": "三根高度不同的债务柱，问号在最小的一根上方"},
            {"do": "展示订阅按钮位置（不要做成夸张动画）",
             "see": "订阅按钮被简单圈出"},
            {"do": "最后回到三问表，提醒观众下次带上自己的数字",
             "see": "空白的 Your number 三格等待填写"},
        ],
        "verify": "CTA 是一个具体动作（评论 MATH / 填三问表），不是空泛的「关注我」。",
        "pitfalls": [
            "不要说「关注我获取更多理财知识」这类空话。",
            "不要承诺下期一定解答某个人的具体情况——那会变成个别投资建议。",
        ],
        "audio": "口播说 comment the word math 时，画面正好展示 MATH 气泡。",
    },
]
